### ISSUE TITLE
Execute functionality exactly once in lifecycle of component

### ISSUE THREAD

**Issue by Poorva17** [Ahnfelt/react4s#14]
Hello @Ahnfelt ,

We want our functionality to get executes exactly once in lifecycle of component. In react.js componentWillMount serves the purpose, but in react4s componentWillMount method is not available. Instead it has **componentWillRender which is called before every render**. 

So we have written our functionality in component constructor.  For that we had to use Get.unsafe as handle to get is NOT available in constructor.

Is this a right pattern?

**Comment by atooni** [comment]
Hello @Poorva17, 

after studying the examples in react4s, we went a different path and you can see an example in 
https://github.com/woq-blended/blended.mgmt.ui/blob/master/mgmt-app/src/main/scala/blended/mgmt/app/components/MgmtMainComponent.scala 

As you can see we are setting up a web socket listener in our compopnent. To avoid doing that in 
every call to **componentWillRender**, we keep the actual listener in an Option and only perform the registration if the Option is still empty. 

Please note, that the example is the top level page of a SPA application and is only mounted once in the 
life-cycle of our app. The app is also under development and it's current state does not yet contain a full fledged solution. This having said, the solution seems to work well for our purpose of having exactly one socket listener per app instance. 

HTH
Andreas

**Comment by mushtaq** [comment]
Our use-case is such that we want to inject something in a component that is *not* a prop, say a `webclient`, just so that we can test the component with a mock. We could think of 2 solutions:

option-1.
```scala
case class MyComp(client: P[WebClient], label: P[String]) extends Component[NoEmit] {
   val localState = State("")
   Get.Unsafe(client).onComplete(//call localState.set)
   def render(get: Get) = ???
}
//calling side
Component(MyComp(client, get(labelProp)))
```
option-2.
```scala
case class MyComp(client: WebClient)(label: P[String]) extends Component[NoEmit] {
   val localState = State("")
   client.onComplete(//call localState.set)
   def render(get: Get) = ???
}
//calling side
Component(MyComp(client) _, get(labelProp))
```

Based on your comment, I guess you would suggest to use option-2? Do I get it right?

**Comment by Ahnfelt** [comment]
I probably lack some context, because it seems to me you don't need to pass WebClient to MyComp at all?

```scala
case class MyComp(value : P[String], label: P[String]) extends Component[NoEmit] {
   def render(get: Get) = ???
}

//somewhere outside
val localState = State[Option[String]](None)
client.onComplete(//call localState.set)
Tags(get(localState).map(v => Component(MyComp, v, get(labelProp))
```

**Comment by mushtaq** [comment]
It is a good point, we can possibly refactor it that way.

Out of curiosity, if some other static (non-prop) data needs to be passed to MyComp, will you recommend using option-2 over option-1? Or this will be an anti-pattern for a react app?

**Comment by Ahnfelt** [comment]
I think there are actually two parts to this question:

### 1. Should WebClient and similar be passed as a prop or something else?

If the `==` operator on WebClient implements structural equality correctly, it should be passed as a prop. Otherwise, it's a bit more involved.

The partial application approach is iffy, because React4s uses the companion object that you normally pass in as the first argument to Component(...) for a couple of things. I'm not sure how well partial application is supported.

### 2. How do you wait for something asynchronous to be initialized?

I can see that the WebClient has an onComplete method. I'm not sure what the precise interface is, but it seems asynchronous. If you can get a Future, then you can use the Loader:

```scala
case class MyComp(client : P[WebClient], label: P[String]) extends Component[NoEmit] {
   val result = Loader(this, client) { _.loadUsingAFuture() }
   def render(get: Get) = ???
}
```

The loader has methods to answer some questions that you'll probably need to ask, eg. is it still loading? did it fail with an error? has it succeeded, and if so, what was the result?

**Comment by mushtaq** [comment]
@Ahnfelt thanks for the explanation! We will have a look at the Loader.
