### ISSUE TITLE
Use materialize css classes in React4s components

### ISSUE THREAD

**Issue by Poorva17** [Ahnfelt/react4s#15]
Hello @Ahnfelt,

We are using React4s way of applying css to components. Css support react4s provides is excellent. 

We have a use case where we want to use css classes provided by [materialize css](https://materializecss.com/) . 

For now one workaround we found is,
We want to have _**TopBarCss**_ (react4s CssClass) and **_read-text_**(materialize css class)
```scala
 E.div(
        TopBarCss,
        A.className("red-text", TopBarCss.name),
        E.span(
          BrandTitleCss,
          Text("My title")
        )
      )
```
What is standard way to do this?

**Comment by atooni** [comment]
Hi @Poorva17, 

it seems that you already have found a way to achieve what you want. Could you elaborate, what else you are after with the issue ? 

Best regards 
Andreas

**Comment by Poorva17** [comment]
Yes @atooni, may be I was not clear. The way I have done is not ideal because I had to repeat TopBarCss.
```scala
E.div(
        **TopBarCss**,
        A.className("red-text", **TopBarCss.name**),
        E.span(
          BrandTitleCss,
          Text("My title")
        )
      )
```

**Comment by atooni** [comment]
Hi @Poorva17, 

AFAIK, the first usage triggers the creation of the inline stylesheet in your resulting html page. Furtheron, you can reference the gererated classname as you did. So in this particular code block I do not see another option. However, if you were sue (!!!) that you have used TopBarCSS already and it is present in your resulting HTML, you could omit the first usage op TopBarCSS in your example. 

My 2ct 
Andreas

**Comment by Poorva17** [comment]
Yes you are right @atooni. As of now we have found one solution mentioned above, 

But my question is more about what is ideal pattern to use React4s css and non-react4s css for some component? Is there any provision in react4s framework itself to handle this.

**Comment by atooni** [comment]
Hi @Poorva17 , 

if the non-react-css comes from an external stylesheet, you can always reference it via the classnames as you did in your example. 

If the external css is defined in SASS or LESS, you need to configure your webpack configuration to include the SASS or LESS preprocessing producing the actual stylesheets. These you would reference in your HTML and again use the classnames as you did. 

If you use something like JSS, I would go and include the instantiation of the JSS classes in my application loader, so that I could then determine the generated classnames and use them as you did in your example. 

You can use inline (adhoc) css definitions and use the withStyles(...) method defined in Material UI.  You can have a look at https://github.com/woq-blended/blended.mgmt.ui/blob/master/material/src/main/scala/blended/ui/material/Material.scala to look at how I have wrapped the withStyles(...) method. 

Best regards 
Andreas

**Comment by Ahnfelt** [comment]
I agree this is not ideal. I can look into making `className` work seamlessly with React4s defined CSS classes, so that you just can write:

      E.div(
        TopBarCss,
        A.className("red-text")
      )

Would you consider that an appropriate solution?

**Comment by Poorva17** [comment]
Sure @Ahnfelt. That will be helpful 👍

**Comment by Poorva17** [comment]
Hello @Ahnfelt , thank you for external css class support 👍 

I have one question regarding composing css classes.
Like in React4s, I can compose css classes **_ResultTitleAreaCss_** and  **_OperationTitleCss_** e.g.-
```scala
object ResultTitleAreaCss
    extends CssClass(
      OperationTitleCss,
      S.position.fixed(),
      S.left("52%"),
      S.top.px(55)
    )
```

Now I am wondering if I  want to compose third party css class say **_red-text_**, is there any way to do this. Or I am not sure is this requirement even feasible using css?

**Comment by Ahnfelt** [comment]
Unfortunately not; the CSS composition feature relies on having access to
the styles of the composed CssClasses at generation time (eg. during
offline rendering).

tir. 14. aug. 2018 kl. 07.38 skrev Poorva Gokhale <notifications@github.com
