### ISSUE TITLE
Using react dev tools with react4s application.

### ISSUE THREAD

**Issue by Poorva17** [Ahnfelt/react4s#20]
Hi @Ahnfelt,

We are writing web application using react4s. We observed that react dev tools shows react4s components being converted as react components. But we are not able see state for those react components. Only stateUpdates counter is seen. 

We have few questions based on this observation - 
1. Does this mean that react4s does not use react local state but something else internally?
2. If react4s uses some other approach other than react local state then I would like to know reasons behind this?

**Comment by Ahnfelt** [comment]
React4s does not use the React.js state to store the current value of the `State(...)`s. Maybe it should - however, there's not enough information available to give it a good field name in the React.js state, and it would prevent State(...) from being updated immediately, since React.js has delayed update for state.

Maybe we can find a way to make the state inspectable somehow in the dev tools?
