### ISSUE TITLE
Impossible to find this library by googling

### ISSUE THREAD

**Issue by mushtaq** [Ahnfelt/react4s#6]
Your library API looks very clean, thanks for creating this lib.

But, if I search scala.js and react.js (or any other variation of those terms), this library never appears in my search results. I wonder how others discovers it. Thought you should know.

**Comment by Taig** [comment]
I found it by searching github for "scalajs react" after being frustrated by the prominent solutions that show up on Google. But I guess it should get there eventually because the repository is raising in popularity and the front page and readme contain the necessary information.

On a sidenote: I'm super curious how Google is coping with your new documentation page @Ahnfelt, that has no SSR. It might be too early yet, but if you made any experiences with that please let me know 🙏

**Comment by Ahnfelt** [comment]
@mushtaq I'm glad you like it! You raise a very central issue.

I'd love to make it easier to find on Google, and I bet there's some SEO there could be done both in the readme and on react4s.org. The moderators of /r/scala were kind enough to add react4s.org to the side bar, which probably helps. Anything you can suggest?

@Taig Thank you for your experinece report. I'll look into how Google treats react4s.org and return with some more details.

Another thing that would help the placement on google is ingoing links - if you like the library, blog posts about it with a link is a good way to help raise the placement on Google.

In general, spreading the word is a great way to contribute to React4s right now! I really struggle with creating awareness around this library, so any help is greatly appreciated!

**Comment by Ahnfelt** [comment]
@Taig Just a quick update: The react4s.org site hasn't been crawled by Google since March 26th. There's no indication of any error in the Google Search Console, and "fetch as Google" works with no issues. It's still a mystery to me.

**Comment by Ahnfelt** [comment]
After doing some more research, I'm concluding that while Google claims to crawl AJAX sites, it does not do so consistently. Their "fetch as googlebot" tool says there are no problems, but there obviously are.

Possible things to try:

- Server side rendering, which I already use elsewhere; but then I'd have to find another host etc.
- Switching to HTTPS - maybe Google doesn't like running scripts on non-HTTPS sites (wild guess).
- Other ideas?

**Comment by Taig** [comment]
[This article](https://www.javascriptstuff.com/react-seo/) suggests that it should generally work. I guess you did the "Fetch as Google" part already so the question is why Google does not execute the js. I doubt your rendering is being deferred by `setTimeout` or an AJAX call. HTTPS might be a likely cause. Another idea is the js size. You are delivering the `fastOptJS` with 1.6MB. You should at least give the `fullOptJS` a try. Maybe declaring all JS dependencies in the `<head />` element might help as well (and should be fine since the page is empty anyway).

**Comment by Ahnfelt** [comment]
@Taig Thank you, those are valid points - I'll take a stab at fixing those tonight.

**Comment by Ahnfelt** [comment]
I've implemented the changes you suggested (minus HTTPS for now). I've also removed the two *crossorigin* script references, since they were also likely culprits. Thank you again for the suggestions; in a few days, we'll know if the problem was solved 👍

**Comment by Ahnfelt** [comment]
The front page is now indexed by Google - thank you for helping out. I'm not sure the subpages are indexed, but there isn't that much text on most of them anyway. 🎉
