### ISSUE TITLE
Confusing behaviour of emit and .withhandler

### ISSUE THREAD

**Issue by Poorva17** [Ahnfelt/react4s#9]
Hello,

Thanks for creating react4s. Really liked it. 

1. I find behaviour of emit and .withhandler confusing. Documentation says
`Instead of updating state locally, you can choose to emit() a message to the parent component, telling it how to update the model for the inner component` on this [page](http://www.react4s.org/). Also if I see emit documentation in IntelliJ I find  - 

`/** Emit a message of type M, which can be handled by a parent component by using .withHandler(...). */
    var emit : M => Unit = { _ => }`

This understanding  and code implemented in [Tree editor example](https://github.com/Ahnfelt/react4s-samples/tree/master/src/main/scala/com/github/ahnfelt/react4s/samples/treeeditor) is not aligned. TreeNodeComponent emits event in renderButton method and is handled in same component (NOT parent component) in renderTodoList. Can you please explain this behaviour?

2. Library [documentation](http://www.react4s.org/) says `React4s has an Elm/Redux-like emit() system` . Does that mean it provide redux like store (single place to store state) and any component (not only parent component) can listen to state change??

**Comment by Ahnfelt** [comment]
Hi Poorva,

Thank you for checking out React4s!

# 1.

The emit() of the TreeNodeComponent is in fact handled by the parent component - it's just that since it's drawing a tree, the parent component may be a TreeNodeComponent itself!

In other words, the .withHandler in TreeNodeComponent does not handle emits from the current component - instead, it handles emits from its child components.

# 2.

You can put all your state in one single State field in the root component of your application, which then acts as the store. If you pass that value down as props to the child components, and have no other State, then you can code in a purely functional style. The tree editor is an example of how to code in this style.

Does that help?

**Comment by Poorva17** [comment]
Thank you @Ahnfelt. Yes this does help in understanding my concerns. You can close this issue 👍

**Comment by Ahnfelt** [comment]
Great! Feel free to ask again if there's anything else.

**Comment by Poorva17** [comment]
Hi @Ahnfelt, 

I want to implement approach which you mentioned `( state in one single State field in the root component which then act as store and pass that value down as props to the child components )`. But in this approach, if child component wants to modify this state I have to go through chain of emits to go back in the hierarchy up to root component, so that other components depending on that state can react to change.

I want to avoid this chain of emits. Is there any way to solve this? 

(Like in redux - any component can emit action to update global store directly. I don't have to traverse hierarchy to update store. )

**Comment by atooni** [comment]
Hi, 
In our application, a management console we use Akka for Scala.JS. Your components could listen on events published on the Akka Event Stream. Our prototypes seem to work well with this approach.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Poorva Gokhale <notifications@github.com> Date: 15/05/2018  07:34  (GMT+01:00) To: Ahnfelt/react4s <react4s@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [Ahnfelt/react4s] Confusing behaviour of emit and .withhandler (#9) 
Hi @Ahnfelt,
I want to implement approach which you mentioned ( state in one single State field in the root component which then act as store and pass that value down as props to the child components ). But in this approach, if child component wants to modify this state I have to go through chain of emits to go back in the hierarchy up to root component, so that other components depending on that state can react to change.
I want to avoid this chain of emits. Is there any way to solve this?
(Like in redux - any component can emit action to update global store directly. I don't have to traverse hierarchy to update store. )

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Ahnfelt/react4s","title":"Ahnfelt/react4s","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Ahnfelt/react4s"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Poorva17 in #9: Hi @Ahnfelt, \r\n\r\nI want to implement approach which you mentioned `( state in one single State field in the root component which then act as store and pass that value down as props to the child components )`. But in this approach, if child component wants to modify this state I have to go through chain of emits to go back in the hierarchy up to root component, so that other components depending on that state can react to change.\r\n\r\nI want to avoid this chain of emits. Is there any way to solve this? \r\n\r\n(Like in redux - any component can emit action to update global store directly. I don't have to traverse hierarchy to update store. )\r\n\r\n "}],"action":{"name":"View Issue","url":"https://github.com/Ahnfelt/react4s/issues/9#issuecomment-389048018"}}}
{"@type":"MessageCard","@context":"http://schema.org/extensions","hideOriginalBody":"false","originator":"37567f93-e2a7-4e2a-ad37-a9160fc62647","title":"Re: [Ahnfelt/react4s] Confusing behaviour of emit and .withhandler (#9)","sections":[{"text":"","activityTitle":"**Poorva Gokhale**","activityImage":"https://avatars3.githubusercontent.com/u/13188905?s=160\u0026v=4","activitySubtitle":"@Poorva17","facts":[]}],"potentialAction":[{"name":"Add a comment","@type":"ActionCard","inputs":[{"isMultiLine":true,"@type":"TextInput","id":"IssueComment","isRequired":false}],"actions":[{"name":"Comment","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueComment\",\"repositoryFullName\":\"Ahnfelt/react4s\",\"issueId\":9,\"IssueComment\":\"{{IssueComment.value}}\"}"}]},{"targets":[{"os":"default","uri":"https://github.com/Ahnfelt/react4s/issues/9#issuecomment-389048018"}],"@type":"OpenUri","name":"View on GitHub"},{"name":"Unsubscribe","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"MuteNotification\",\"threadId\":332309182}"}],"themeColor":"26292E"}

**Comment by Ahnfelt** [comment]
Hi @Poorva17,

There's no built-in support in React4s for emitting events directly to a global event handler. This is intentional, since it's at odds with modularity. 

Take the tree example - if the emits went directly to a global event handler, each node in the tree would have to know its own location in the global state, in order to construct an event that can update the right part of the global state. Thus, the TreeNodeComponent would cease to be a resuable component and instead become a component that can be used only in a specific place in the application.

However, if you want to do this regardless, I can show how implement it as an Attachable.

**Comment by Ahnfelt** [comment]
Here's a quick implementation. I'm not an expert on Redux, so you'll have to tell me if it lacks anything (it probably does).


# Implementation

This is a general class for all global stores, with messages of type M and state of type S:

```scala
abstract class GlobalStore[M, S](initialValue : S) {

    private val listeners = mutable.HashSet[Component[_]]()
    private var storedValue = initialValue

    def onEmit(message : M, currentValue : S) : S

    def emit(message : M) : Unit = {
        storedValue = onEmit(message, storedValue)
        for(listener <- listeners) listener.update()
    }

    def apply(component : Component[_]) : Signal[S] =
        component.attach(new Signal[S] with Attachable {
            listeners += component
            override def componentWillUnmount(get : Get) : Unit = listeners -= component
            override def sample(get : Get) : S = storedValue
        }
    )
}
```

In short, it keeps track of who's listening for state updates, and expects `onEmit` to be overriden to define what happens when a message is emitted.


# Usage

Define a single concrete store for your application somewhere. Here you'll specify how to update the state whenever a message arrives. 

```scala
object VotesGlobalStore extends GlobalStore[Boolean, Int](0) {
    override def onEmit(vote : Boolean, currentValue : Int) = {
        if(vote) currentValue + 1 else currentValue - 1
    }
}
```

Of course, in realistic examples, the Boolean would be sum type representing the possible messages as in the tree editor example, and the state would likely be a record instead of an Int.

Once you have done this, you can access the state and emit from all your components like this:

```scala
case class VoteComponent() extends Component[NoEmit] {
    val votes = VotesGlobalStore(this)

    override def render(get : Get) = {
        E.div(
            Text(get(votes) + " votes "),
            E.button(Text("Vote up"), A.`type`("button"), A.onLeftClick(_ => VotesGlobalStore.emit(true))),
            E.button(Text("Vote down"), A.`type`("button"), A.onLeftClick(_ => VotesGlobalStore.emit(false)))
        )
    }
}
```

**Comment by avitaln** [comment]
I recommend using diode https://diode.suzaku.io/
With diode, the whole application behavior is maintained in the application model regardless of the UI components.
By using it, you can pass the whole application model to the root component (as a prop) and from the root component - pass only the relevant part to the other inner components.
the inner component notify their change using emit, and the root component notify the application model changes using diode mechanism: AppCircuit.dispatch( action )
This helps keep the application immutable

**Comment by Poorva17** [comment]
Thank you all for suggestions 👍 . We are now exploring which approach suits best our application.

**Comment by Poorva17** [comment]
Hi @Ahnfelt , 

We found that `Global store` approach is good fit for our application. 
1.  I would like to know why is it not part of library? 
2. Also earlier you mentioned `There's no built-in support in React4s for emitting events directly to a global event handler. This is intentional, since it's at odds with modularity.`. I would like to know more about this.

**Comment by mushtaq** [comment]
@avitaln My impression based on the diode docs was it works with scalajs-react. But your response indicates that it may work with React4s as well. Will be interesting to check it out. Thanks.

**Comment by avitaln** [comment]
@mushtaq Integration with react4s requires additional 2 lines of code:
Just need to declare the State member and subscribe to changes which will trigger state changes

```
case class MainComponent() extends Component[NoEmit] {
  val rootModelState: State[RootModel] = State(AppCircuit.initialModel)
  AppCircuit.subscribe(AppCircuit.zoom(identity))(modelRO ⇒ rootModelState.set(modelRO()))
 .
 .
 .
}
```

- MainComponent is the top level component of the application.
- RootModel is the top level case class which hold the entire application model.
- AppCircuit (object AppCircuit extends Circuit[RootModel]) implements the application logic (intercepting actions and modifying the model),
-

**Comment by Ahnfelt** [comment]
Well, consider the case of a simple toggle button.

We can write it using a global store for the application:

```scala
case class ToggleButtonComponent() extends Component[NoEmit] {

    val global = MyGlobalStore(this)

    override def render(get : Get) =
        E.div(
            ToggleCss,
            E.div(SliderCss, SliderToggledCss.when(get(global).autosave)),
            E.div(HandleCss, HandleToggledCss.when(get(global).autosave)),
            A.onLeftClick(_ => MyGlobalState(emit(SetAutosave(!get(global).autosave))))
        )

}
```

The problem is, now the toggle button mentions `autosave` and `SetAutosave`. So it can only be used to toggle whether or not the application autosaves. If I wanted another toggle button to toggle whether or not to check spelling, eg. `global.spellCheck`, I'd have to create another `ToggleButtonComponent`!

If instead it's written with props and emit, as in the example [here](http://www.react4s.org/examples/toggle-button), I could simply use the same ToggleButtonComponent for both switches:

```scala
E.div(Text("Autosave"), Component(ToggleButtonComponent, get(autosave)).withHandler(autosave.set)),
E.div(Text("Autosave"), Component(ToggleButtonComponent, get(spellCheck)).withHandler(spellCheck.set))
```

**Comment by mushtaq** [comment]
@avitaln Thanks will have a look.

**Comment by Poorva17** [comment]
@Ahnfelt Thank you for explanation. 👍

**Comment by bilal-fazlani** [comment]
@avitaln Your comment helped me a lot. 

I have one more question about using react4s with diode

`val rootModelState: State[RootModel] = State(AppCircuit.initialModel)` . Here it seems we are maintaining a copy of global state in local state of the component. This seems a little unconventional when compared to pure react-redux approach. In a pure js app, we don't usually duplicate global and local state. I think what we do there, is we push global state into components as `props`. 

Is this necessary to use local state when you use diode or combination of react4s and diode?
